name: Workflow-CI

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # 1. Set up job 

      # 2. Checkout repository
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      # 3. Set up Python
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # 4. Check Env
      - name: Check Env
        run: |
          python --version
          pip --version

      # 5. Install dependencies
      - name: Install dependencies
        run: |
          pip install -r MLProject/requirements.txt
          pip install mlflow dagshub

      # 6. Run MLflow project
      - name: Run MLflow project
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/lyaaaaa04/SMSML_Alya.mlflow
        run: |
          mlflow run MLProject/ --env-manager=local --experiment-name=student_performance-ci

      # 7. Get latest MLflow run_id
      - name: Get latest MLflow run_id
        id: get_run
        run: |
          RUN_ID=$(mlflow runs list --experiment-name Student_performance_CI --max-results 1 | awk 'NR==3{print $1}')
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      # 8. Install Python dependencies (optional)
      - name: Install Python dependencies
        run: |
          pip install mlflow

      # 9. Upload model ke GitHub Artifacts
      - name: Upload trained model (GitHub Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLProject/models/

      # 10. Build Docker Model
      - name: Build Docker Model
        run: |
          docker build -t student_model:latest MLProject/

      # 11. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 12. Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag student_model:latest ${{ secrets.DOCKER_USERNAME }}/workflow-ci:latest

      # 13. Push Docker Image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/workflow-ci:latest

      # 14. Post steps (otomatis)
      # 15. Complete job
