name: Workflow-CI

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache conda environment
        uses: actions/cache@v3
        with:
          path: ~/.conda/envs/mlflow-env
          key: ${{ runner.os }}-conda-env-${{ hashFiles('MLProject/conda.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-env-

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          activate-environment: mlflow-env
          environment-file: MLProject/conda.yml
          auto-activate-base: false
          use-mamba: true

      - name: Run MLflow project
        run: |
          mlflow run MLProject/ --env-manager=local --experiment-name=Student_performance_CI
        shell: bash -l {0}

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/model.pkl

  docker:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}   

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: MLProject
          file: MLProject/docker
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/workflow-ci:latest
